### ISSUE TITLE
feat(#4):utilities and fix git in order to refactor code

### ISSUE THREAD

**Issue by david13penalver** [javferTec/digiFramework#4]

**Comment by david13penalver** [comment]
xxxs
xxs
xs
s
m
l
xl
xxl
xxxl

**Comment by david13penalver** [comment]
Border-radius:
0px, 2px, 4px, 8px, 12px, 16px, **_50%_**

¿Nombres?

**Comment by david13penalver** [comment]
> Border-radius: 0px, 2px, 4px, 8px, 12px, 16px, **_50%_**
> 
> ¿Nombres?

xs s m l xl

**Comment by david13penalver** [comment]
> > Border-radius: 0px, 2px, 4px, 8px, 12px, 16px, **_50%_**
> > ¿Nombres?
> 
> xs s m l xl

--border-radius-#{$value}

**Comment by javferTec** [comment]
> xxxs xxs xs s m l xl xxl xxxl

para margin, padding, borders

**Comment by javferTec** [comment]
// FONT FAMILY
$font-sans-serif: "Arial", "Helvetica", sans-serif;
$font-serif: "Georgia", "Times New Roman", Times, serif;
$font-monospace: "Courier New", Courier, monospace;

// FONT SIZE
$font-size-xxxs: 8px;
$font-size-xxs: 10px;
$font-size-xs: 12px;
$font-size-s: 14px;
$font-size-m: 16px;
$font-size-l: 18px;
$font-size-xl: 20px;
$font-size-xxl: 24px;
$font-size-xxxl: 32px;

// FONT WEIGHT
$font-weight-light: 300;
$font-weight-normal: 400;
$font-weight-bold: 700;

// MARGIN
$margin-xxxs: 4px;
$margin-xxs: 8px;
$margin-xs: 12px;
$margin-s: 16px;
$margin-m: 24px;
$margin-l: 32px;
$margin-xl: 48px;
$margin-xxl: 64px;
$margin-xxxl: 96px;

// PADDING
$padding-xxxs: 4px;
$padding-xxs: 8px;
$padding-xs: 12px;
$padding-s: 16px;
$padding-m: 24px;
$padding-l: 32px;
$padding-xl: 48px;
$padding-xxl: 64px;
$padding-xxxl: 96px;

// BORDER RADIUS
$border-radius-xs: 2px;
$border-radius-s: 4px;
$border-radius-m: 8px;
$border-radius-l: 16px;
$border-radius-xl: 32px;

// BORDER WIDTH
$border-width-xs: 1px;
$border-width-s: 2px;
$border-width-m: 4px;
$border-width-l: 8px;
$border-width-xl: 16px;

// BORDER-HEIGHT
$border-height-xs: 1px;
$border-height-s: 2px;
$border-height-m: 4px;
$border-height-l: 8px;
$border-height-xl: 16px;

**Comment by david13penalver** [comment]
Shadows:

$shadows: (
    "none": none,
    "s": 0 1px 2px rgba(0, 0, 0, 0.05),
    "mm": 0 4px 6px rgba(0, 0, 0, 0.1),
    "l": 0 10px 15px rgba(0, 0, 0, 0.15),
    "xl": 0 20px 25px rgba(0, 0, 0, 0.2)
);
